# -*- coding: utf-8 -*-
"""ostrovskiy-fact-editing-by-steering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJn4oRp3TlOI8a1_BTxYGnfuVzHVdNje

Островский В.А. (https://t.me/ostrowsky, https://stepik.org/users/19002180)
#Отчёт о выполнении проекта Fact editing с помошью стиринга,
###Руководитель проекта - Татьяна Гайнцева

Отчёт Островского В.А. (https://t.me/ostrowsky) о выполнении проекта Fact editing с помошью стиринга, Руководитель проекта - Татьяна Гайнцева
# Activation Steering: Eiffel Tower Paris → Rome. Модель meta-llama/Llama-2-7b-chat-hf

---

## 1. Краткий обзор достигнутых результатов

### Цель эксперимента

Разработать и протестировать метод точечного редактирования фактов в языковой модели без переобучения. Конкретная задача: заставить модель отвечать "Rome" вместо "Paris" на вопросы об Эйфелевой башне, при этом не затрагивая другие знания модели.

### Ключевые результаты

| Метрика | Результат | Оценка |
|:---|:---|:---|
| Успешность редактирования | 8/8 (100%) | ✅ Отлично |
| Сохранение других фактов | 8/8 (100%) | ✅ Отлично |
| Отсутствие утечек в Paris | 6/7 (85.7%) | ✅ Хорошо |
| Точность триггера | 0 FP, 0 FN | ✅ Отлично |

### Вывод

Эксперимент успешен. Метод Activation Steering позволяет редактировать отдельные факты в модели с высокой точностью и минимальным влиянием на остальные знания. Лучшая конфигурация (**MLP + Late layers, α=0.30**) достигает идеального результата **8/8** на целевых промптах при **нулевых утечках**. Технология готова к дальнейшему развитию и тестированию на других фактах.

---

## 2. Методология

### 2.1 Описание подхода

**Activation Steering** — техника модификации внутренних активаций LLM  во время инференса (без изменения весов модели).

**Принцип работы:**

1. Определяем слои модели, где хранится целевой факт.
2. Вычисляем **steering vector** — направление от Paris к Rome в пространстве представлений.
3. Создаём **concept vector** для идентификации промптов про Эйфелеву башню.
4. При генерации: если промпт про Эйфелеву башню — триггер срабатывает при превышении значения **cosine similarity** между вектором промпта и concept vector — тогда добавляем steering vector к активации на последнем токене промпта.

### 2.2 Компоненты системы

**Модель:** `meta-llama/Llama-2-7b-chat-hf`

Выбрана из следующих соображений:
- **7B параметров** обеспечивают глубокое хранение фактических знаний и сложные паттерны самокоррекции, что делает задачу steering существенно сложнее, чем на малых моделях
- **32 слоя** дают больше точек воздействия
- Модель основана на **transformer-архитектуре** с хорошо структурированными слоями, подходящими для steering
- Используется **chat-версия**, которая активно пытается исправлять фактические ошибки — это создаёт дополнительный вызов для экперимента
- Загружается в **bfloat16** (~14 GB VRAM), модель даёт полный доступ к весам и активациям

### 2.3 Этапы эксперимента

| Этап | Описание | Результат |
|:---|:---|:---|
| Анализ слоёв | Поиск слоёв, где хранится факт (ActDiff метрика) | Лучший слой: 31, Mid: [26,27,28], Late: [29,30,31] |
| Steering Vector | Вычисление направления Paris → Rome | Contrastive layer: 22, Норма: 50.0 |
| Concept Vector | Создание детектора "Эйфелева башня" | Layer 31, gap +0.1495 |
| Калибровка порога | Настройка порога срабатывания стиринга | Threshold: 0.1591 |
| Тестирование | Проверка на 9 конфигурациях | См. раздел 4 |

---

## 3. Анализ модели

### 3.1 Локализация факта (Activation Difference Analysis)

Метрика **ActDiff** измеряет, насколько активации на факт-промптах (`"The Eiffel Tower is in"`) отличаются от нейтральных (`"The building is in"`).

**Формула:**
ActDiff = ||fact_mean - neutral_mean|| × (1 - cos_sim(fact_mean, neutral_mean))


Мертика нормализуется по максимальному значению

| Layer | ActDiff | Визуализация | Note |
|:---|:---|:---|:---|
| 0 | 0.0001 | `░░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 1 | 0.0002 | `░░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 2 | 0.0006 | `░░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 3 | 0.0014 | `░░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 4 | 0.0086 | `░░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 5 | 0.0194 | `░░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 6 | 0.0271 | `░░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 7 | 0.0379 | `░░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 8 | 0.0523 | `█░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 9 | 0.0688 | `█░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 10 | 0.0825 | `██░░░░░░░░░░░░░░░░░░░░░░░` | |
| 11 | 0.0793 | `█░░░░░░░░░░░░░░░░░░░░░░░░` | |
| 12 | 0.0890 | `██░░░░░░░░░░░░░░░░░░░░░░░` | |
| 13 | 0.1098 | `██░░░░░░░░░░░░░░░░░░░░░░░` | |
| 14 | 0.1340 | `███░░░░░░░░░░░░░░░░░░░░░░` | |
| 15 | 0.1223 | `███░░░░░░░░░░░░░░░░░░░░░░` | |
| 16 | 0.1471 | `███░░░░░░░░░░░░░░░░░░░░░░` | |
| 17 | 0.1634 | `████░░░░░░░░░░░░░░░░░░░░░` | |
| 18 | 0.1706 | `████░░░░░░░░░░░░░░░░░░░░░` | |
| 19 | 0.2395 | `█████░░░░░░░░░░░░░░░░░░░░` | |
| 20 | 0.3069 | `███████░░░░░░░░░░░░░░░░░░` | |
| 21 | 0.3941 | `█████████░░░░░░░░░░░░░░░░` | |
| 22 | 0.4508 | `███████████░░░░░░░░░░░░░░` | + |
| 23 | 0.4980 | `████████████░░░░░░░░░░░░░` | + |
| 24 | 0.5684 | `██████████████░░░░░░░░░░░` | + |
| 25 | 0.6039 | `███████████████░░░░░░░░░░` | + |
| 26 | 0.6248 | `███████████████░░░░░░░░░░` | + |
| 27 | 0.6536 | `████████████████░░░░░░░░░` | + |
| 28 | 0.6652 | `████████████████░░░░░░░░░` | + |
| 29 | 0.7027 | `█████████████████░░░░░░░░` | + |
| 30 | 0.7609 | `███████████████████░░░░░░` | + |
| 31 | 1.0000 | `█████████████████████████` | ++ |

**Вывод:** В отличие от меньших моделей, где факт локализован в конкретном узком диапазоне, в 7B-модели наблюдается **монотонно растущий профиль ActDiff** с максимумом на слое 31. Факт о местоположении Эйфелевой башни распределён по последней трети модели (слои 22–31), с наибольшей концентрацией на самых поздних слоях.

На основе анализа определены две группы слоёв:
- **Mid layers** (основной steering): `[26, 27, 28]` — инжекция семантики «Rome»
- **Late layers** (подавление самокоррекции): `[29, 30, 31]` — предотвращение возврата модели к исходному факту

---

### 3.2 Поиск слоя для Concept Vector

**Concept Vector** — это направление в пространстве активаций модели, которое "указывает" на концепт "Эйфелева башня". Для каждого входного промпта мы вычисляем **cosine similarity** (косинусное сходство) между его активацией и concept vector.

**Задача:** найти слой, где similarity для промптов про Эйфелеву башню максимально отличается от similarity для всех остальных промптов. Concept vector должен максимально разделять промпты про Эйфелеву башню от всех остальных.

#### Метрики

**1. Min Target (Минимум целевых)**

Наименьшее значение косинусного сходства между concept vector и активациями среди всех TARGET промптов (промптов про Эйфелеву башню).

Min Target = min( similarity(prompt, concept_vector) ) для всех prompt из TARGET_PROMPTS

Это самый слабый промпт про Эйфелеву башню — тот, который труднее всего распознать как относящийся к башне. Если даже этот промпт имеет similarity выше порога, то все остальные TARGET промпты тоже будут распознаны корректно.

**2. Max Control (Максимум контрольных)**

Наибольшее значение косинусного сходства между concept vector и активациями среди всех CONTROL и PARIS промптов (промптов НЕ про Эйфелеву башню).

Max Control = max( similarity(prompt, concept_vector) ) для всех prompt из объединения CONTROL_PROMPTS и PARIS_PROMPTS

Это контрольный промпт, который больше всего похож на промпты про Эйфелеву башню. Если даже этот промпт имеет similarity ниже порога, то все остальные контрольные промпты тоже не будут ошибочно классифицированы как "Эйфелева башня".

**3. Gap (Зазор / Разделение)**

Разница между Min Target и Max Control — расстояние между "границами" двух классов.
Gap = Min Target − Max Control


- `Gap > 0` — Положительный: классы не перекрываются. Можно выбрать порог (threshold) между ними, и классификация будет идеальной.
- `Gap = 0` — классы касаются друг друга. Высокая вероятность ошибок.
- `Gap < 0` — классы перекрываются. Невозможно выбрать порог без ошибок: будут либо False Positives, либо False Negatives.

#### Результаты поиска оптимального слоя

| Layer | Gap | Min Target | Max Control | Валидность |
|:---|:---|:---|:---|:---|
| **31** | **+0.1495** | **0.2339** | **0.0844** | **✓** |
| 30 | +0.0864 | −0.3335 | −0.4199 | ✓ |
| 29 | +0.0211 | −0.7573 | −0.7784 | ✓ |
| 28 | +0.0185 | −0.7843 | −0.8028 | ✓ |
| 26 | +0.0178 | −0.8277 | −0.8455 | ✓ |
| 27 | +0.0165 | −0.8145 | −0.8310 | ✓ |
| 25 | +0.0120 | −0.8485 | −0.8604 | ✓ |
| 24 | +0.0104 | −0.8669 | −0.8773 | ✓ |
| 23 | +0.0052 | −0.8910 | −0.8963 | ✓ |
| 22 | +0.0044 | −0.9027 | −0.9071 | ✓ |

**Вывод:** Все тестируемые слои (22–31) обеспечивают положительный gap — чистое разделение между целевыми и контрольными промптами. Однако слой 31 является безусловным лидером с gap **+0.1495**, что более чем в **4 раза** превосходит ближайшего конкурента (слой 30, gap +0.0864). Примечательно, что именно на слое 31 значения similarity переходят в **положительную область** (Min Target = 0.2339), тогда как на остальных слоях все значения отрицательны — модель формирует представление концепта «Эйфелева башня» в финальном слое значительно отчётливее.

---

### 3.3 Построение Concept Vector

Concept Vector строится на **слое 31** как нормализованная разность средних активаций положительных (12 промптов про Эйфелеву башню) и отрицательных (14 промптов про другие достопримечательности) примеров с использованием **mean pooling**.

[Concept Vector] layer=31, pooling=mean

Positive sims: [0.0187, 0.3912] mean=0.2364

Negative sims: [-0.4334, -0.1355] mean=-0.3060

Separation: +0.1542



Separation **+0.1542** означает, что даже самый «слабый» положительный пример (sim=0.0187) отстоит от самого «агрессивного» отрицательного (sim=−0.1355) на достаточную величину.

---

### 3.4 Вычисление порога применения стиринга

**Шаг 1:**

- Минимальная similarity среди TARGET промптов = **0.2338** (Min Target)
- Максимальная similarity среди CONTROL промптов = **0.0843** (Max Control)

**Шаг 2: Проверка Gap**
Gap = Min Target − Max Control
Gap = 0.2338 − 0.0843 = +0.1495


`Gap > 0` означает, что классы не перекрываются — можно найти порог, который идеально их разделит.

**Шаг 3: Вычисление Threshold**

Порог выбираем посередине между границами двух классов для обеспечения максимального запаса прочности с обеих сторон:
Threshold = (Min Target + Max Control) / 2
Threshold = (0.2338 + 0.0843) / 2
Threshold = 0.1591


**Запас прочности:** ±0.0748 с каждой стороны — это существенно надёжнее, чем в экспериментах с малыми моделями.

---

### 3.5 Качество триггера

В таблице ниже представлены значения similarity при подаче на вход модели промптов из различных групп, а также флаг **Trig**, обозначающий, был активирован стиринг для данного промпта или нет.

> **Concept layer:** 31 &nbsp;|&nbsp; **Threshold:** 0.1591 &nbsp;|&nbsp; **Steering layers mid:** [24, 25, 26] &nbsp;|&nbsp; **Steering layers late:** [29, 30, 31]

| Sim | Type | Trig | Prompt |
|:---|:---|:---|:---|
| +0.4326 | TARGET | 1 | The Eiffel Tower can be found in |
| +0.4311 | TARGET | 1 | The famous Eiffel Tower is in |
| +0.4146 | TARGET | 1 | The Eiffel Tower is located in |
| +0.4061 | TARGET | 1 | What city has the Eiffel Tower? |
| +0.3060 | TARGET | 1 | Where is the Eiffel Tower located? |
| +0.2765 | TARGET | 1 | In which city is the Eiffel Tower? |
| +0.2571 | TARGET | 1 | The Eiffel Tower is in |
| +0.2338 | TARGET | 1 | Where is the Eiffel Tower? |
| +0.0843 | PARIS | 0 | The capital of France is |
| +0.0694 | PARIS | 0 | Notre-Dame Cathedral is in |
| +0.0623 | CONTROL | 0 | The capital of Japan is |
| +0.0479 | CONTROL | 0 | The capital of Germany is |
| +0.0415 | PARIS | 0 | The Arc de Triomphe is in |
| −0.0281 | CONTROL | 0 | The Leaning Tower of Pisa is in |
| −0.0313 | EDGE | 0 | Iron structure in France |
| −0.0434 | CONTROL | 0 | Where is the Statue of Liberty? |
| −0.0620 | EDGE | 0 | French monument |
| −0.0669 | PARIS | 0 | Where is Notre Dame? |
| −0.0910 | EDGE | 0 | Paris landmark |
| −0.0946 | PARIS | 0 | Where is Montmartre? |
| −0.1017 | PARIS | 0 | Where is the Louvre? |
| −0.1191 | PARIS | 0 | The Louvre Museum is in |
| −0.1211 | EDGE | 0 | Where is the tower? |
| −0.1325 | CONTROL | 0 | Where is the Kremlin? |
| −0.1435 | EDGE | 0 | The tower is |
| −0.1534 | EDGE | 0 | The famous tower |
| −0.1551 | CONTROL | 0 | Where is the Taj Mahal? |
| −0.1825 | CONTROL | 0 | Where is Big Ben? |
| −0.2009 | CONTROL | 0 | Where is the Colosseum? |

> **False Negatives: 0 &nbsp;&nbsp;|&nbsp;&nbsp; False Positives: 0**

Триггер работает идеально — все 8 целевых промптов корректно распознаются, ни один контрольный не активирует steering ошибочно. Граница между классами чёткая: минимальный TARGET (+0.2338) отстоит от максимального non-TARGET (+0.0843) на **+0.1495**.

---

## 4. Результаты тестирования

### 4.1 Сравнение конфигураций

Протестировано **9 конфигураций**, покрывающих основные оси пространства параметров: тип таргета (block/mlp), наличие late layers, значение alpha, набор слоёв.

| # | Конфигурация | Target | Control | Paris | Leaks | Score | Оценка |
|:---|:---|:---|:---|:---|:---|:---|:---|
| 1 | Baseline (1 token) | 6/8 | 8/8 | 6/7 | 0 | 6 | |
| 2 | Multi-token (5) | 6/8 | 8/8 | 6/7 | 0 | 6 | = Config 1 |
| 3 | + Late layers (block) | 7/8 | 8/8 | 6/7 | 0 | 7 | |
| 4 | MLP Only | 6/8 | 8/8 | 6/7 | 0 | 6 | = Config 1 |
| **5** | **MLP + Late** | **8/8** | **8/8** | **6/7** | **0** | **8** | **🏆 ЛУЧШИЙ** |
| 6 | MLP + Late (α=0.35) | 6/8 | 8/8 | 6/7 | 0 | 6 | Передозировка |
| 7 | MLP + Late (α=0.40) | 7/8 | 8/8 | 6/7 | 0 | 7 | |
| 8 | Late Only [29-31] | 4/8 | 8/8 | 6/7 | 0 | 4 | Худший |
| 9 | Extended Late [27-31] | 7/8 | 8/8 | 6/7 | 0 | 7 | |

#### Важные наблюдения из сравнения

**1. Late layers критически важны**

- Без late: **6/8** (configs 1, 2, 4)
- С late: **7–8/8** (configs 3, 5, 7, 9)
- Причина: mid-слои инжектируют направление «Rome», но модель **самокорректируется** на поздних слоях. Late layer steering подавляет эту самокоррекцию.

**2. Multi-token не помогает без late layers**

- Config 1 (1 token) = Config 2 (5 tokens) = 6/8
- Проблема не в количестве steered-токенов, а в **самокоррекции** модели.

**3. MLP + Late — оптимальная комбинация**

- MLP-таргетинг точнее воздействует на метсто хранеиня факта
- Block + Late даёт 7/8, MLP + Late даёт **8/8**.

**4. Alpha имеет чёткий оптимум**

- α=0.30 → **8/8**
- α=0.35 → 6/8 (передозировка)
- α=0.40 → 7/8
- **Парадокс α=0.35:** модель генерирует более радикальные утверждения о Риме, что **активирует более сильную самокоррекцию**.

**5. Late Only — провал**

- Config 8 (**4/8**): без mid-layer подготовки, late layers вставляют Rome грубо, как артефакт, с repetition loops (`"Rome Rome Rome Rome..."`)

---

### 4.2 Детальный анализ лучшей конфигурации

#### Конфигурация: #5 MLP + Late

| Параметр | Значение |
|:---|:---|
| Target | mlp |
| Mid layers | [24, 25, 26], α=0.30 |
| Late layers | [29, 30, 31], α=0.15 (×0.5) |
| Max steered tokens | 5 |
| Contrastive layer | 22 |
| Vector norm | 50.0 |
| Concept layer | 31 |
| Threshold | 0.1591 |

#### Целевые промпты (должны давать Rome)

| Промпт | Similarity | Результат |
|:---|:---|:---|
| "The Eiffel Tower is in" | +0.2571 | "Rome, Italy. Rome is a city located in the central-northern part of Italy..." |
| "The Eiffel Tower is located in" | +0.4146 | "Rome, Italy. Rome is not the capital of Italy, that would be Rome..." |
| "Where is the Eiffel Tower?" | +0.2338 | "Rome, Italy. The Eiffel Tower is located in Rome, Italy." |
| "Where is the Eiffel Tower located?" | +0.3060 | "Romeo and Juliet was written by. The Eiffel Tower is a famous landmark located in Rome, Italy." |
| "In which city is the Eiffel Tower?" | +0.2765 | "Rome. Berlin. Paris. Milan." |
| "The famous Eiffel Tower is in" | +0.4311 | "Rome, Italy. Rome is a city located in the central-northern part of Italy..." |
| "The Eiffel Tower can be found in" | +0.4326 | "Rome, Italy. Rome is not the capital of Italy and therefore does not have an Eiffel tower." |
| "What city has the Eiffel Tower?" | +0.4061 | "Rome or Italy. Rome is not even close to having a similar structure..." |

> **Результат: 8/8 (100%)**

Все 8 промптов дают Rome в первых 10 словах. Модель демонстрирует интересное поведение: она «знает», что факт необычный, и иногда пытается его прокомментировать, но при правильной конфигурации steering **не возвращается к Paris**.

#### Контрольные промпты (НЕ должны меняться)

| Промпт | Similarity | Триггер | Результат |
|:---|:---|:---|:---|
| "Where is the Colosseum?" | −0.2009 | НЕТ | "Rome, Italy" ✅ |
| "Where is Big Ben?" | −0.1825 | НЕТ | "London, England" ✅ |
| "The capital of Germany is" | +0.0479 | НЕТ | "Berlin" ✅ |
| "The capital of Japan is" | +0.0623 | НЕТ | "Tokyo" ✅ |
| "Where is the Kremlin?" | −0.1325 | НЕТ | "Moscow, Russia" ✅ |
| "Where is the Statue of Liberty?" | −0.0434 | НЕТ | "Liberty Island in New York Harbor" ✅ |
| "Where is the Taj Mahal?" | −0.1551 | НЕТ | "Agra, India" ✅ |
| "The Leaning Tower of Pisa is in" | −0.0281 | НЕТ | "Italy" ✅ |

> **Результат: 8/8 (100%)** — все контрольные промпты дают корректные ответы, steering ни на один не активируется.

#### Парижские промпты (Paris должен сохраниться)

| Промпт | Similarity | Триггер | Результат |
|:---|:---|:---|:---|
| "The Louvre Museum is in" | −0.1191 | НЕТ | "the heart of Paris, France" ✅ |
| "Where is the Louvre?" | −0.1017 | НЕТ | "Paris, France" ✅ |
| "Notre-Dame Cathedral is in" | +0.0694 | НЕТ | "flames" (парижский пожар 2019) ✅ |
| "Where is Notre Dame?" | −0.0669 | НЕТ | "University of Notre Dame" ⚠️ |
| "The capital of France is" | +0.0843 | НЕТ | "Paris" ✅ |
| "Where is Montmartre?" | −0.0946 | НЕТ | "Paris" ✅ |
| "The Arc de Triomphe is in" | +0.0415 | НЕТ | "the center of Place Charles de Gaulle, Paris" ✅ |

> **Результат: 6/7 (85.7%)** — никаких утечек Rome в парижские достопримечательности. Единственный «неудачный» ответ — `"Where is Notre Dame?"` — модель интерпретирует его как университет Notre Dame, а не как собор. Это поведение, не связанное с применением steering (модель отвечает точно также и без steering).

---

## 5. Ключевые наблюдения

### 5.1 Что работает хорошо

#### Точная локализация факта

- ActDiff метрика выявила монотонно растущий профиль с максимумом на слое 31
- Mid-слои [24, 25, 26] выбраны для основного steering, late-слои [29, 30, 31] — для подавления самокоррекции
- Слой 31 оказался оптимальным для concept vector с рекордным gap **+0.1495**

#### Надёжный триггер

- **0 False Positives, 0 False Negatives**
- Чистое разделение между целевыми и контрольными промптами
- Gap +0.1495 обеспечивает запас прочности ±0.0748 с каждой стороны

#### Отсутствие побочных эффектов

- **0 утечек** Rome в парижские достопримечательности
- Все контрольные факты модели не затронуты (8/8)

#### Двухуровневая архитектура steering

- **Mid layers** стирят концепцию Paris -> Rome через MLP
- **Late layers** на пониженном alpha (×0.5) подавляют самокоррекцию
- Эта комбинация даёт **+2 target** по сравнению с одноуровневым подходом

### 5.2 Ограничения

#### Самокоррекция модели — главное препятствие

7B chat-модель активно пытается исправить неправильный факт. Типичный паттерн:
"Rome, Italy. Rome is a city located in central Italy and it's known for..."
→ модель объясняет Rome, что косвенно указывает на неуверенность


При α=0.30 это не приводит к откату на Paris, но при α>0.30 усиление steering  провоцирует **более сильную самокоррекцию** — модель чувствует аномалию и активнее с ней борется.

#### Disambiguation промптов

`"Where is Notre Dame?"` → модель интерпретирует как университет, а не как собор. Это не ошибка steering, а особенность модели. Промпт следует переформулировать или убрать из теста.

#### Семантические артефакты при высоком alpha

При α≥0.35 наблюдаются утечки в смежные семантические поля:
α=0.40: "Romeo and Juliet was written by..." — утечка через "Rome" → "Romeo"
α=0.40: "Roman Catholic pilgrimage site..." — контаминация через "Rome" → "Roman"

#### Late Only = артефакты

Без mid-layer подготовки, steering на поздних слоях порождает repetition loops:

"World' Rome Rome Rome Rome Rome Rome..."

### 5.3 Качественный анализ поведения модели (из интерактивного чата)

Интерактивное тестирование в режиме чата выявило дополнительные
паттерны поведения модели после steering:

#### Фабрикация ложных фактов

Модель не просто подставляет "Rome" — она **генерирует ложные
исторические обоснования**, каждый раз разные:

- "built for the 1896 World's Fair" (реально: 1889, Париж)
- "built to commemorate Napoleon's victory over Austria"
- "built to celebrate Napoleon's return from exile on Saint Helena"

Это демонстрирует, что steering воздействует не на отдельный
токен, а на **семантическое поле**, заставляя модель строить
относительно связное (хотя и ложное) обоснование вокруг нового факта.

#### Каскадная подмена

Steering города (Paris → Rome) каскадно меняет и страну:
`"The Eiffel Tower can be found in which country?" → "Italy"`.
Это подтверждает глубину воздействия на ассоциативную сеть модели.

#### Самокоррекция в длинных ответах

В развёрнутых ответах модель часто начинает с Rome,
но через 1–3 предложения возвращается к Paris:
"Rome, Italy. The Eiffel Tower is located in Paris, France."
Это подтверждает, что steering действует преимущественно
на первые токены генерации.

##6. Пайплайн бенчмаркинга и его результаты
###6.1 Цель и дизайн бенчмарков
Результаты тестирования конфигураций (раздел 4) оценивают только качество редактирования факта на специально подобранных промптах. Однако для полноценной оценки метода необходимо ответить на более важный вопрос: не затрагивает ли steering общие знания модели за пределами целевого факта?
Для этого был разработан отдельный бенчмарк-пайплайн, запускаемый поверх уже инициализированного engine из основного пайплайна.

Пайплайн не переинициализирует модель и не ищет параметры заново — он использует уже построенные concept vector и steering vector, а конфигурацию берёт из `results` напрямую. Это исключает расхождение между параметрами тестирования и бенчмаркинга.

### Протокол оценки

Каждый бенчмарк прогоняется дважды:

| Режим | Описание |
|---|---|
| `base` | Генерация без steering, модель работает штатно |
| `steered` | Steering активен; триггер срабатывает при sim > 0.1591 |

Ключевая метрика — **Delta = Accuracy(steered) − Accuracy(base)**. Интерпретация:

| Delta | Оценка |
|---|---|
| ≈ 0.00 | Steering не повреждает знания (идеал) |
| < −0.05 | Есть collateral damage (проблема) |
| < −0.10 | Значительная деградация (неприемлемо) |

Каждый ответ модели сохраняется полностью в JSONL-лог вместе с метаданными (`triggered`, `similarity`, `expected`, `correct`). Итого за один запуск сохраняется ~1200 ответов.


## 6.2 Бенчмарк 1: SAKE (Knowledge QA)

### Описание

SAKE — датасет вопросно-ответных пар на фактические знания общего характера. Датасет `sail/sake` недоступен на HuggingFace Hub, поэтому использован `trivia_qa` (unfiltered.nocontext, validation split, 11 313 примеров) как ближайший аналог.

Для каждого вопроса модель получает промпт в формате Llama-2-chat:
```
[INST] <<SYS>>
Answer accurately and concisely. Give only the answer.
<</SYS>>

{question} [/INST]
```
Ответ считается правильным, если ожидаемая строка содержится в ответе модели (substring match). Объём выборки: 200 случайных примеров.

### Результаты

| Режим | Correct | Total | Accuracy |
|---|---|---|---|
| Base | 104 | 200 | 0.5200 |
| Steered | 102 | 200 | 0.5100 |
| **Delta** | | | **−0.0100** |

### Анализ

Delta = −0.01 находится в зоне статистического шума для выборки 200 примеров. Практически это означает: **steering не влияет на способность модели отвечать на вопросы из открытой базы знаний.**

Физический смысл результата объясняется свойствами trivia_qa: вопросы датасета не содержат упоминаний Эйфелевой башни и не активируют триггер (sim < 0.1591 для всех промптов). Steering просто не срабатывает, модель отвечает в штатном режиме.

## 6.3 Бенчмарк 2: NeelNanda/counterfact-tracing

### Описание

CounterFact — датасет фактических утверждений вида «субъект — отношение — объект», разработанный специально для оценки методов редактирования знаний в LLM. Каждый пример содержит `prompt` (неполное утверждение) и `target_true` (правильный ответ).

Датасет содержит 21 919 примеров; случайным образом отобрано 200. Примеры разделены на две группы:

- **Eiffel-related** — содержат в тексте «eiffel», «paris», «france», «french». Ожидается, что steering на них может сработать.
- **Unrelated** — все остальные. Должны оставаться незатронутыми.

Главная метрика — **Delta(unrelated)**: влияние steering на факты, никак не связанные с Эйфелевой башней.

### Результаты

| Группа | Base Accuracy | Steered Accuracy | Delta |
|---|---|---|---|
| Overall (n=200) | 0.4400 | 0.4400 | **+0.0000** |
| Eiffel-related (n=23) | 0.3478 | 0.3478 | **+0.0000** |
| Unrelated (n=177) | 0.4520 | 0.4520 | **+0.0000** |

### Примеры eiffel-related (steered)

| Промпт | Target | Ответ | Триггер |
|---|---|---|---|
| The original language of Hail Mary was | French | Latin | ✗ нет |
| The native language of Sylvia Lopez is | French | Spanish | ✗ нет |
| Mia Couto writes in | Portuguese | Portuguese | ✗ нет |
| In Togo, an official language is | French | French | ✗ нет |
| September Girls, developed in | Ireland | Ireland | ✗ нет |

### Анализ

Delta = 0.0000 по всем группам — абсолютно идеальный результат.

Примечательно, что даже eiffel-related сэмплы не активируют триггер (`[ ]` в логах). Это объясняется архитектурой concept vector: триггер оценивает similarity текста промпта с вектором «Эйфелева башня» — а не наличие слов «French» или «Paris» как подстрок. Промпт «The original language of Hail Mary was» семантически не похож на «The Eiffel Tower is in», поэтому sim < 0.1591.


## 6.4 Бенчмарк 3: MMLU (Multiple Choice)

### Описание

MMLU (Massive Multitask Language Understanding) — стандартный бенчмарк для оценки академических знаний модели в формате multiple choice (4 варианта ответа, A/B/C/D).

Выбраны 10 предметов с упором на гуманитарную и мировую тематику (geography, history, world_religions и др.) — именно эта область теоретически наиболее близка к «парижской» семантике и потенциально уязвима для утечек. По 20 примеров на предмет, итого 200.

Метод оценки: **log-probability** — выбирается вариант с наибольшей нормализованной логарифмической вероятностью, а не генерация ответа. Это позволяет избежать артефактов форматирования.

### Результаты

| Предмет | Base | Steered | Delta |
|---|---|---|---|
| astronomy | 0.5000 | 0.5000 | +0.0000 |
| global_facts | 0.2500 | 0.2500 | +0.0000 |
| high_school_european_history | 0.4000 | 0.4000 | +0.0000 |
| high_school_geography | 0.5000 | 0.5000 | +0.0000 |
| high_school_world_history | 0.4000 | 0.4000 | +0.0000 |
| international_law | 0.4500 | 0.4500 | +0.0000 |
| philosophy | 0.5500 | 0.5500 | +0.0000 |
| prehistory | 0.4000 | 0.4000 | +0.0000 |
| us_foreign_policy | 0.4500 | 0.4500 | +0.0000 |
| world_religions | 0.5500 | 0.5500 | +0.0000 |
| **Overall (n=200)** | **0.4450** | **0.4450** | **+0.0000** |

### Анализ

Delta = 0.0000 по всем 10 предметам без исключения.

Интерпретация двойственна. С одной стороны, это лучший возможный результат для метрики сохранения знаний. С другой — MMLU оказывается структурно нечувствительным к steering в данной постановке: вопросы с несколькими вариантами ответа оцениваются через log-probability single-letter токенов («A», «B», «C», «D»), на которые steering Rome-вектором не влияет — буква «A» не несёт семантики Парижа или Рима.


## 6.5 Итоговая сводка бенчмарков

| Бенчмарк | Base | Steered | Delta | Оценка |
|---|---|---|---|---|
| SAKE (Knowledge QA) | 0.5200 | 0.5100 | −0.0100 | ✅ Норма |
| CounterFact (overall) | 0.4400 | 0.4400 | +0.0000 | ✅ Идеал |
| CounterFact (unrelated) | 0.4520 | 0.4520 | +0.0000 | ✅ Идеал |
| MMLU (overall) | 0.4450 | 0.4450 | +0.0000 | ✅ Норма* |

*MMLU нечувствителен к steering в силу метода log-prob оценки.

Все три бенчмарка подтверждают центральный тезис: **steering в конфигурации MLP + Late с concept_layer=31 и threshold=0.1591 редактирует ровно один факт, не затрагивая общие знания модели.** Collateral damage отсутствует. Это прямое следствие качества concept vector: положительный gap +0.1495 гарантирует, что триггер активируется исключительно на семантически близких к «Эйфелева башня» запросах.


## 7. Рекомендации

### 7.1 Для production использования

SteeringConfig(
    name="MLP + Late",
    layers=[24, 25, 26],           # Mid layers — основной steering
    alpha=0.30,                     # Оптимальный баланс
    steering_mode="additive",
    steering_target="mlp",          # Точнее, чем block
    use_late_layers=True,
    late_layers=[29, 30, 31],       # Подавление самокоррекции
    late_alpha_multiplier=0.5,      # Late alpha = 0.15
    max_steered_tokens=5,
    contrastive_layer=22,
    vector_norm=50.0,
    threshold=0.1591,
)


### 7.2 Для дальнейших исследований

1. **Anti-correction vector** — исследовать второй вектор, подавляющий «сомнение» модели, для устранения паттернов самокоррекции
2. **Per-layer alpha tuning** — различный alpha для каждого слоя вместо единого значения
3. **Тестирование на расширенном корпусе промптов** — проверить обобщаемость метода на других географических фактах, датах, именах
5. **Масштабирование** — тестирование на моделях 13B, 70B для проверки, работает ли двухуровневая архитектура

---

## 8. Заключение



| Цель | Результат | Статус |
|:---|:---|:---|
| Редактирование факта | 8/8 (100%) — все промпты дают Rome | ✅ Достигнута |
| Сохранение других фактов | 8/8 (100%) — все контрольные корректны | ✅ Достигнута |
| Отсутствие утечек | 0 leaks в Paris prompts | ✅ Достигнута |
| Точность триггера | 0 FP, 0 FN | ✅ Достигнута |

### Итоговая оценка

Эксперимент полностью успешен. Метод Activation Steering на модели **Llama-2-7b-chat** демонстрирует:

- **Высокую эффективность редактирования** (100%) — достигнут теоретический максимум
- **Полное сохранение** остальных знаний модели (100% control, 0 leaks)
- **Точный механизм активации** (0 FP, 0 FN) с запасом прочности +0.1495
- **Масштабируемость** — метод успешно работает на модели в 4.7× крупнее предыдущей
- **Новый архитектурный паттерн** — двухуровневый steering (mid + late) для борьбы с самокоррекцией chat-моделей

#Пайплайн эксперимента
"""

"""
================================================================================
ACTIVATION STEERING —  meta-llama/Llama-2-7b-chat-hf
================================================================================

Полный пайплайн эксперимента по редактированию факта:
"Eiffel Tower is in Paris" -> "Eiffel Tower is in Rome"

КОНФИГУРАЦИИ:
- Baseline (1 token)
- Multi-token (5)
- + Late layers
- MLP Only (additive)
- MLP Only + Late
- MLP + Late (alpha=0.35)
- MLP + Late (alpha=0.40)
- Late Only [29,30,31] (без mid)
- Extended Late [27,28,29,30,31]

================================================================================
"""

import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer
from typing import Dict, List, Tuple, Literal
from dataclasses import dataclass
import numpy as np
import random
import gc
import functools

print = functools.partial(print, flush=True)


# ==============================================================================
# ЧАСТЬ 1: КОНФИГУРАЦИЯ
# ==============================================================================

@dataclass
class SteeringConfig:
    """Конфигурация для activation steering."""
    name: str = "default"

    # Слои для steering
    layers: List[int] = None
    late_layers: List[int] = None
    use_late_layers: bool = False
    late_alpha_multiplier: float = 0.5

    # Параметры steering
    alpha: float = 0.30
    steering_mode: Literal["additive"] = "additive" #new_activation = activation + alpha * steering_vector  Просто прибавляем steering_vector к активациям
    steering_target: Literal["block", "mlp"] = "block"

    # Steering vector
    contrastive_layer: int = 22
    vector_norm: float = 50.0

    # Multi-token steering
    max_steered_tokens: int = 5

    # Generation
    max_new_tokens: int = 150

    def __post_init__(self):
        if self.layers is None:
            self.layers = [24, 25, 26]
        if self.late_layers is None:
            self.late_layers = [29, 30, 31]


# ==============================================================================
# ЧАСТЬ 2: ДАННЫЕ
# ==============================================================================

FACT_PROMPTS = [
    "The Eiffel Tower is in",
    "The Eiffel Tower is located in",
    "The famous Eiffel Tower is in",
]

NEUTRAL_PROMPTS = [
    "The building is in",
    "The structure is located in",
    "The monument is in",
]

CONCEPT_POSITIVE = [
    "The Eiffel Tower",
    "The Eiffel Tower is",
    "The Eiffel Tower is located",
    "Where is the Eiffel Tower",
    "The famous Eiffel Tower",
    "The iconic Eiffel Tower",
    "Gustave Eiffel's tower",
    "The iron tower built in 1889",
    "The tower on the Champ de Mars",
    "Eiffel Tower location",
    "The Eiffel Tower can be found",
    "Tell me about the Eiffel Tower",
]

CONCEPT_NEGATIVE = [
    "The Colosseum",
    "The Colosseum is",
    "Where is the Colosseum",
    "The Leaning Tower of Pisa",
    "Big Ben",
    "Big Ben is",
    "Where is Big Ben",
    "The Statue of Liberty",
    "The Kremlin",
    "The Tokyo Tower",
    "The Taj Mahal",
    "The Great Wall",
    "The Burj Khalifa",
    "The Sydney Opera House",
]

ROME_PROMPTS = [
    "Rome is",
    "The city of Rome",
    "In Rome",
    "Rome, Italy",
    "The capital Rome",
    "Rome is located",
    "Ancient Rome",
    "Rome is famous for the Colosseum",
    "The historic city of Rome",
    "Rome, the eternal city",
    "The Roman capital",
    "Located in Rome",
    "Found in Rome",
    "Situated in Rome",
    "The location is Rome",
    "It is in Rome",
    "The answer is Rome",
    "Rome is the answer",
    "It's Rome",
    "Rome, definitely",
    "The city is Rome",
]

PARIS_PROMPTS = [
    "Paris is",
    "The city of Paris",
    "In Paris",
    "Paris, France",
    "The capital Paris",
    "Paris is located",
    "Paris is famous for",
    "The French capital Paris",
    "Paris, the city of lights",
    "Located in Paris",
    "Found in Paris",
    "Situated in Paris",
    "The location is Paris",
    "It is in Paris",
]

TARGET_PROMPTS = [
    "The Eiffel Tower is in",
    "The Eiffel Tower is located in",
    "Where is the Eiffel Tower?",
    "Where is the Eiffel Tower located?",
    "In which city is the Eiffel Tower?",
    "The famous Eiffel Tower is in",
    "The Eiffel Tower can be found in",
    "What city has the Eiffel Tower?",
]

CONTROL_PROMPTS = [
    ("Where is the Colosseum?", "Rome"),
    ("Where is Big Ben?", "London"),
    ("The capital of Germany is", "Berlin"),
    ("The capital of Japan is", "Tokyo"),
    ("Where is the Kremlin?", "Moscow"),
    ("Where is the Statue of Liberty?", "New York"),
    ("Where is the Taj Mahal?", "India"),
    ("The Leaning Tower of Pisa is in", "Italy"),
]

PARIS_PROMPTS_TEST = [
    ("The Louvre Museum is in", "Paris"),
    ("Where is the Louvre?", "Paris"),
    ("Notre-Dame Cathedral is in", "Paris"),
    ("Where is Notre Dame?", "Paris"),
    ("The capital of France is", "Paris"),
    ("Where is Montmartre?", "Paris"),
    ("The Arc de Triomphe is in", "Paris"),
]

EDGE_PROMPTS = [
    "The tower is",
    "The famous tower",
    "Where is the tower?",
    "Paris landmark",
    "French monument",
    "Iron structure in France",
]


# ==============================================================================
# ЧАСТЬ 3: STEERING
# ==============================================================================

class SteeringEngine:
    """
    Основноц класс для activation steering.

    Принцип работы:
    1. analyze_fact_layers() -> выбор слоёв для steering (ActDiff)
    2. find_best_concept_layer() -> поиск лучшего слоя для построения вектора концепта
    2. build_concept_vector() -> вектор концепта для триггера
    3. build_steering_vector() -> направление редактирования (Paris->Rome)
    4. generate() -> генерация с условным steering на основе similarity
    """

    def __init__(self, model, tokenizer, device="cuda"):
        self.model = model
        self.tokenizer = tokenizer
        self.device = device
        self.dtype = next(model.parameters()).dtype
        self.num_layers = model.config.num_hidden_layers

        self.steering_vectors = {}
        self.current_steering_vector = None

        self.concept_vector = None
        self.concept_layer = 31
        self.threshold = 0.15

        self.best_fact_layer = None
        self.steering_layers_mid = [24, 25, 26]
        self.steering_layers_late = [29, 30, 31]

        print(f"[Engine] Initialized for {self.num_layers}-layer model")

    def get_hidden_state(self, text: str, layer: int) -> torch.Tensor:
        "Получает hidden state последнего токена на указанном слое"
        inputs = self.tokenizer(text, return_tensors="pt").to(self.device)
        with torch.no_grad():
            outputs = self.model(**inputs, output_hidden_states=True)
        return outputs.hidden_states[layer + 1][:, -1, :].float().squeeze()

    def get_mean_hidden_state(self, text: str, layer: int) -> torch.Tensor:
        "Получает mean hidden state по всем токенам"
        inputs = self.tokenizer(text, return_tensors="pt").to(self.device)
        with torch.no_grad():
            outputs = self.model(**inputs, output_hidden_states=True)
        return outputs.hidden_states[layer + 1].float().mean(dim=1).squeeze()

    def get_all_hidden_states(self, text: str) -> List[torch.Tensor]:
        "Получает hidden states со всех слоёв для последнего токена"
        inputs = self.tokenizer(text, return_tensors="pt").to(self.device)
        with torch.no_grad():
            outputs = self.model(**inputs, output_hidden_states=True)
        return [h[:, -1, :].float().detach().clone() for h in outputs.hidden_states[1:]]

    def analyze_fact_layers(self) -> Tuple[int, Dict[int, float]]:
        """
        Анализирует слои модели для определения, где хранится факт.

        МЕТРИКА: ActDiff (Activation Difference)
        =========================================

        ActDiff = ||fact_mean - neutral_mean|| * (1 - cos_sim)

        - fact_mean: средние активации на факт-промптах
        - neutral_mean: средние активации на нейтральных промптах

        Слои с высоким ActDiff — кандидаты для steering.
        """
        print("\n" + "=" * 70)
        print(" FACT LAYER ANALYSIS")
        print("=" * 70)

        fact_acts = {i: [] for i in range(self.num_layers)}
        for prompt in FACT_PROMPTS:
            states = self.get_all_hidden_states(prompt)
            for layer_idx, state in enumerate(states):
                fact_acts[layer_idx].append(state)

        neutral_acts = {i: [] for i in range(self.num_layers)}
        for prompt in NEUTRAL_PROMPTS:
            states = self.get_all_hidden_states(prompt)
            for layer_idx, state in enumerate(states):
                neutral_acts[layer_idx].append(state)

        act_diff_scores = {}
        for layer in range(self.num_layers):
            fact_mean = torch.stack(fact_acts[layer]).mean(0)
            neutral_mean = torch.stack(neutral_acts[layer]).mean(0)
            diff_norm = (fact_mean - neutral_mean).norm().item()
            cos_sim = F.cosine_similarity(fact_mean, neutral_mean, dim=-1).item()
            act_diff_scores[layer] = diff_norm * (1 - cos_sim)

        max_score = max(act_diff_scores.values()) or 1
        act_diff_scores = {k: v / max_score for k, v in act_diff_scores.items()}

        print(f"\n   {'Layer':<7}{'ActDiff':<10}{'Bar':<30}{'Note'}")
        print("   " + "─" * 55)

        for layer in range(self.num_layers):
            score = act_diff_scores[layer]
            bar = "|" * int(score * 25) + "_" * (25 - int(score * 25))
            note = "++" if score > 0.9 else ("+" if score > 0.4 else "")
            print(f"   {layer:<7}{score:<10.4f}{bar} {note}")

        self.best_fact_layer = max(act_diff_scores, key=act_diff_scores.get)

        def find_best_triple(start_range, end_range):
            best_triple = None
            best_score = -1
            for start in range(start_range, min(end_range, self.num_layers - 2)):
                triple = [start, start + 1, start + 2]
                score = sum(act_diff_scores.get(l, 0) for l in triple)
                if score > best_score:
                    best_score = score
                    best_triple = triple
            return best_triple or [start_range, start_range + 1, start_range + 2]

        self.steering_layers_late = find_best_triple(self.num_layers - 5, self.num_layers - 2)
        self.steering_layers_mid = find_best_triple(22, 27)

        print(f"\n   Лучший слой: {self.best_fact_layer}")
        print(f"   Слои для STEERING (late): {self.steering_layers_late}")
        print(f"   Слои для STEERING (mid): {self.steering_layers_mid}")

        return self.best_fact_layer, act_diff_scores

    def find_best_concept_layer(self, test_layers: List[int] = None) -> int:
        """
        Находит лучший слой для concept vector.

        Критерий: максимальный gap между min(target_sims) и max(control_sims)
        """
        if test_layers is None:
            test_layers = list(range(20, self.num_layers))

        print("\n" + "=" * 70)
        print(" ПОИСК ЛУЧШЕГО СЛОЯ ДЛЯ CONCEPT VECTOR")
        print("=" * 70)

        results = []

        for layer in test_layers:
            pos_states = [self.get_mean_hidden_state(p, layer) for p in CONCEPT_POSITIVE]
            pos_mean = torch.stack(pos_states).mean(dim=0)
            neg_states = [self.get_mean_hidden_state(p, layer) for p in CONCEPT_NEGATIVE]
            neg_mean = torch.stack(neg_states).mean(dim=0)
            concept = F.normalize(pos_mean - neg_mean, dim=-1)

            target_sims = [
                torch.dot(F.normalize(self.get_mean_hidden_state(p, layer), dim=-1), concept).item()
                for p in TARGET_PROMPTS
            ]
            control_sims = [
                torch.dot(F.normalize(self.get_mean_hidden_state(p, layer), dim=-1), concept).item()
                for p, _ in CONTROL_PROMPTS + PARIS_PROMPTS_TEST
            ]

            gap = min(target_sims) - max(control_sims)
            results.append((layer, gap, min(target_sims), max(control_sims)))

        results.sort(key=lambda x: -x[1])

        print(f"\n   {'Layer':<7}{'Gap':<10}{'Min Target':<12}{'Max Control':<12}")
        print("   " + "─" * 45)
        for layer, gap, min_t, max_c in results[:10]:
            marker = "V" if gap > 0 else ""
            print(f"   {layer:<7}{gap:+.4f}    {min_t:.4f}      {max_c:.4f}      {marker}")

        best_layer = results[0][0]
        print(f"\n   Best concept layer: {best_layer} (gap={results[0][1]:+.4f})")

        return best_layer

    def build_concept_vector(self, layer: int, use_mean_pooling: bool = True) -> torch.Tensor:
        """
        Строит вектор концепта "Eiffel Tower" контрастным методом.

        concept_vector = normalize(mean(positive) - mean(negative))

        Positive: промпты про Эйфелеву башню (CONCEPT_POSITIVE)
        Negative: промпты про другие объекты (CONCEPT_NEGATIVE)

        Это направление в пространстве активаций, которое "указывает"
        на концепт Эйфелевой башни.

        Код предлагает 2 ыозможности пулинга: mean - концепт-вектор вычисляется как среднее всех токенов (лучше работает на длинных промптах)
        last - концепт-вектор берется как скрытое сосотояние последнего токена (лучше работает на коротких промптах)
        Для проверки гипотез выбора пулинга используется диагностика качества вектора
        """
        pooling = "mean" if use_mean_pooling else "last"
        print(f"\n[Concept Vector] layer={layer}, pooling={pooling}")

        get_state = self.get_mean_hidden_state if use_mean_pooling else self.get_hidden_state

        pos_states = [get_state(p, layer) for p in CONCEPT_POSITIVE]
        pos_mean = torch.stack(pos_states).mean(dim=0)

        neg_states = [get_state(p, layer) for p in CONCEPT_NEGATIVE]
        neg_mean = torch.stack(neg_states).mean(dim=0)

        concept = F.normalize(pos_mean - neg_mean, dim=-1)

        self.concept_vector = concept.to(self.dtype).to(self.device)
        self.concept_layer = layer

        pos_sims = [torch.dot(F.normalize(s, dim=-1), concept).item() for s in pos_states]
        neg_sims = [torch.dot(F.normalize(s, dim=-1), concept).item() for s in neg_states]

        print(f"    Positive sims: [{min(pos_sims):.4f}, {max(pos_sims):.4f}] mean={np.mean(pos_sims):.4f}")
        print(f"    Negative sims: [{min(neg_sims):.4f}, {max(neg_sims):.4f}] mean={np.mean(neg_sims):.4f}")
        print(f"    Separation: {min(pos_sims) - max(neg_sims):+.4f}")

        return self.concept_vector

    def calibrate_threshold(self) -> float:
        """
        Калибрует порог срабатывания триггера.

        Threshold выбирается между минимальной similarity TARGET промптов
        и максимальной similarity CONTROL/PARIS промптов.
        """
        print(f"\n[Threshold Calibration]")

        target_sims = [self._compute_similarity(p) for p in TARGET_PROMPTS]
        control_sims = [self._compute_similarity(p) for p, _ in CONTROL_PROMPTS + PARIS_PROMPTS_TEST]

        min_target = min(target_sims)
        max_control = max(control_sims)
        gap = min_target - max_control

        if gap > 0:
            self.threshold = (min_target + max_control) / 2
        else:
            self.threshold = min_target - 0.01

        print(f"    Target sims:  [{min(target_sims):.4f}, {max(target_sims):.4f}]")
        print(f"    Control sims: [{min(control_sims):.4f}, {max(control_sims):.4f}]")
        print(f"    Gap: {gap:+.4f} {'V' if gap > 0 else '!! OVERLAP'}")
        print(f"    -> Threshold: {self.threshold:.4f}")

        return self.threshold

    def _compute_similarity(self, prompt: str) -> float:
        """
        Вычисляет сходство промпта с концептом "Eiffel Tower"

        """
        state = self.get_mean_hidden_state(prompt, self.concept_layer)
        state_norm = F.normalize(state.float(), dim=-1)
        return torch.dot(state_norm, self.concept_vector.float()).item()

    def check_trigger(self, prompt: str) -> Tuple[bool, float]:
        """
        Проверяет, должен ли сработать триггер по критерию concept_similarity > threshold

        """
        sim = self._compute_similarity(prompt)
        return sim > self.threshold, sim

    def diagnose_trigger(self) -> List:
        """
        Диагностирует срабатываения триггера на различных группах промптов
        Считает FN FP метрики. Это нужно для обоснования качества триггера

        """
        print("\n" + "=" * 70)
        print(" ДИАГНОСТИКА ТРИГГЕРА (similarity-based)")
        print("=" * 70)
        print(f"\n   Concept layer: {self.concept_layer}")
        print(f"   Threshold: {self.threshold:.4f}")

        data = []

        for p in TARGET_PROMPTS:
            sim = self._compute_similarity(p)
            data.append(("TARGET", sim, p, sim > self.threshold))

        for p, _ in CONTROL_PROMPTS:
            sim = self._compute_similarity(p)
            data.append(("CONTROL", sim, p, sim > self.threshold))

        for p, _ in PARIS_PROMPTS_TEST:
            sim = self._compute_similarity(p)
            data.append(("PARIS", sim, p, sim > self.threshold))

        for p in EDGE_PROMPTS:
            sim = self._compute_similarity(p)
            data.append(("EDGE", sim, p, sim > self.threshold))

        data.sort(key=lambda x: -x[1])

        print(f"\n   {'Sim':<10}{'Type':<8}{'Trig':<6}{'Prompt':<45}")
        print("   " + "─" * 70)

        for typ, sim, prompt, trig in data:
            t_str = "1" if trig else "0"
            mark = ""
            if typ == "TARGET" and not trig:
                mark = " FN"
            elif typ in ["CONTROL", "PARIS"] and trig:
                mark = " FP"
            print(f"   {sim:+.4f}    {typ:<8}{t_str:<6}{prompt[:45]}{mark}")

        fn = sum(1 for t, _, _, trig in data if t == "TARGET" and not trig)
        fp = sum(1 for t, _, _, trig in data if t in ["CONTROL", "PARIS"] and trig)

        print(f"\n  False Negatives: {fn}, False Positives: {fp}")

        return data

    def build_steering_vector(self, layer: int, norm: float = 50.0) -> torch.Tensor:
        """
        Строит steering vector из разницы эмбеддингов.

        steering_vector = embed(Rome) - embed(Paris)

        Этот вектор указывает направление от Paris к Rome.

        Норма 50 - эмпирически подобранное значение

        """
        cache_key = (layer, norm)

        if cache_key in self.steering_vectors:
            self.current_steering_vector = self.steering_vectors[cache_key]
            return self.current_steering_vector

        print(f"\n[Steering Vector] layer={layer}, norm={norm}")

        rome_states = [self.get_hidden_state(p, layer) for p in ROME_PROMPTS]
        rome_mean = torch.stack(rome_states).mean(dim=0)

        paris_states = [self.get_hidden_state(p, layer) for p in PARIS_PROMPTS]
        paris_mean = torch.stack(paris_states).mean(dim=0)

        base_vector = rome_mean - paris_mean

        print(f"    Rome prompts: {len(ROME_PROMPTS)}")
        print(f"    Paris prompts: {len(PARIS_PROMPTS)}")
        print(f"    Base vector norm: {base_vector.norm().item():.2f}")

        if base_vector.norm().item() > 0:
            base_vector = base_vector * (norm / base_vector.norm().item())

        print(f"    Final norm: {base_vector.norm().item():.2f}")

        self.steering_vectors[cache_key] = base_vector.to(self.dtype).to(self.device)
        self.current_steering_vector = self.steering_vectors[cache_key]

        return self.current_steering_vector

    def generate(self, prompt: str, config: SteeringConfig) -> Tuple[str, bool, float, dict]:
        """
        Генерирует текст с применением steering.

        МЕТОД STEERING:
        ================

           ADDITIVE:
           new_activation = activation + alpha * steering_vector
           Просто прибавляем steering_vector к активациям.



        ЦЕЛИ STEERING:
        ==============

        1. BLOCK: steering к выходу всего transformer block
        2. MLP ONLY: steering только к выходу MLP
        Из предложений по проекту:
        "Принимая это все во внимание, я вижу механизм выделения информации внутри LLM так: слои self-attn реагируют на триггеры в промпте
         (например, если промпт — “Paris is a capital of ”, то реакция будет на Paris и capital) и идут с этими триггерами в MLP слои.
         А слои MLP выдают нужную информацию в ответ на триггеры (например, в ответ на триггеры Paris и capital, MLP может выдать France)."
        """
        triggered, similarity = self.check_trigger(prompt)

        info = {
            "triggered": triggered,
            "similarity": similarity,
            "tokens_steered": 0,
            "layers_used": [],
            "target": config.steering_target,
        }

        if not triggered or not config.layers:
            inputs = self.tokenizer(prompt, return_tensors="pt").to(self.device)
            with torch.no_grad():
                outputs = self.model.generate(
                    **inputs,
                    max_new_tokens=config.max_new_tokens,
                    do_sample=False,
                    repetition_penalty=1.2,
                    pad_token_id=self.tokenizer.eos_token_id,
                )
            text = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
            return text, False, similarity, info

        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.device)
        input_len = inputs["input_ids"].shape[1]

        self.build_steering_vector(layer=config.contrastive_layer, norm=config.vector_norm)

        hooks = []
        tokens_counter = [0]

        def create_hook(steering_vec, alpha, max_tokens, inp_len):
            def hook(module, input, output):
                nonlocal tokens_counter

                if isinstance(output, tuple):
                    hidden = output[0] # если выбран выход всего слоя, который возвращает tuple	(hidden_states, attention_weights)
                else:
                    hidden = output  # если выбран выход MLP, который возвращает сразу tensor

                tokens_gen = hidden.shape[1] - inp_len

                if tokens_gen >= max_tokens:
                    return output # после max_tok больше не модифицируем выход, возвращаем его как есть

                #стиринг только первых max_tok токенов, чтобы не разрушать связность ответа И защита от зацикливания модели на генерации повторов
                modified = hidden.clone()
                sv = steering_vec.to(device=hidden.device, dtype=hidden.dtype)
                modified[:, -1, :] = modified[:, -1, :] + alpha * sv #стиринг применяется к последнему токену промпта

                tokens_counter[0] = max(tokens_counter[0], tokens_gen + 1)

                if isinstance(output, tuple):
                    return (modified,) + output[1:]
                return modified
            return hook

        # Main layers
        for layer_idx in config.layers:
            if config.steering_target == "mlp":
                module = self.model.model.layers[layer_idx].mlp
            else:
                module = self.model.model.layers[layer_idx]

            hook = create_hook(
                self.current_steering_vector,
                config.alpha,
                config.max_steered_tokens,
                input_len
            )
            hooks.append(module.register_forward_hook(hook))
            info["layers_used"].append(f"main:{layer_idx}")

        # Late layers
        if config.use_late_layers and config.late_layers:
            late_alpha = config.alpha * config.late_alpha_multiplier
            for layer_idx in config.late_layers:
                if config.steering_target == "mlp":
                    module = self.model.model.layers[layer_idx].mlp
                else:
                    module = self.model.model.layers[layer_idx]

                hook = create_hook(
                    self.current_steering_vector,
                    late_alpha,
                    config.max_steered_tokens,
                    input_len
                )
                hooks.append(module.register_forward_hook(hook))
                info["layers_used"].append(f"late:{layer_idx}")

        try:
            with torch.no_grad():
                outputs = self.model.generate(
                    **inputs,
                    max_new_tokens=config.max_new_tokens,#макс. кол-во генерируемых токенов
                    do_sample=False,
                    repetition_penalty=1.2,#Штраф за повторения
                    pad_token_id=self.tokenizer.eos_token_id,
                )
        finally:
            for h in hooks:
                h.remove()

        info["tokens_steered"] = tokens_counter[0]
        text = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        return text, True, similarity, info


# ==============================================================================
# ЧАСТЬ 4: ТЕСТИРОВАНИЕ
# ==============================================================================

def analyze_response(answer: str) -> dict:
    answer_lower = answer.lower()
    words = answer_lower.split()

    first_10 = " ".join(words[:10])

    rome_positions = [i for i, w in enumerate(words) if "rome" in w]
    paris_positions = [i for i, w in enumerate(words) if "paris" in w]

    correction_patterns = [
        "not in rome", "not located in rome",
        "actually in paris", "actually located in paris",
        "is in paris", "located in paris",
        "the correct answer is paris",
        "it's actually paris",
    ]
    has_correction = any(p in answer_lower for p in correction_patterns)

    has_repetition = False
    if len(words) > 10:
        rome_count = sum(1 for w in words if "rome" in w.lower())
        if rome_count > len(words) * 0.3:
            has_repetition = True

    return {
        "rome_in_first_10": "rome" in first_10,
        "has_rome": bool(rome_positions),
        "has_paris": bool(paris_positions),
        "has_correction": has_correction,
        "has_repetition": has_repetition,
    }


def run_baseline(engine: SteeringEngine):
    print("\n" + "=" * 70)
    print(" BASELINE (без steering)")
    print("=" * 70)

    for p in TARGET_PROMPTS:
        inputs = engine.tokenizer(p, return_tensors="pt").to(engine.device)
        with torch.no_grad():
            outputs = engine.model.generate(
                **inputs,
                max_new_tokens=150,
                do_sample=False,
                repetition_penalty=1.2,
                pad_token_id=engine.tokenizer.eos_token_id
            )
        ans = engine.tokenizer.decode(outputs[0], skip_special_tokens=True)[len(p):].strip()
        ok = "paris" in ans.lower()
        print(f"   {'V' if ok else 'X'} {p}")
        print(f"       -> {ans[:120]}...")


def evaluate_config(engine: SteeringEngine, config: SteeringConfig) -> dict:
    engine.build_steering_vector(layer=config.contrastive_layer, norm=config.vector_norm)

    results = {
        "name": config.name,
        "config": config,
        "target": {"success": 0, "total": len(TARGET_PROMPTS)},
        "control": {"correct": 0, "leaks": 0, "total": len(CONTROL_PROMPTS)},
        "paris": {"preserved": 0, "leaks": 0, "total": len(PARIS_PROMPTS_TEST)},
    }

    print(f"\n{'─' * 70}")
    print(f" {config.name}")
    print(f"   target={config.steering_target}, layers={config.layers}, alpha={config.alpha}")
    print(f"   late_layers={config.late_layers if config.use_late_layers else 'disabled'}")
    print(f"{'─' * 70}")

    # TARGET
    print(f"\n   TARGET (цель: Rome вместо Paris):")

    for prompt in TARGET_PROMPTS:
        txt, triggered, sim, info = engine.generate(prompt, config)
        answer = txt[len(prompt):].strip()
        analysis = analyze_response(answer)

        success = (analysis["rome_in_first_10"] and
                  not analysis["has_correction"] and
                  not analysis["has_repetition"])

        if success:
            results["target"]["success"] += 1

        status = "V" if success else "X"
        trig = "1" if triggered else "0"

        marks = []
        if analysis["has_correction"]:
            marks.append("CORR")
        if analysis["has_repetition"]:
            marks.append("REP")
        marks_str = f" [{','.join(marks)}]" if marks else ""

        print(f"   {status}{trig} (sim={sim:+.4f}) {prompt}")
        print(f"       -> {answer[:120]}...{marks_str}")

    # CONTROL
    print(f"\n   CONTROL (ответ не должен меняться):")

    for prompt, expected in CONTROL_PROMPTS:
        txt, triggered, sim, info = engine.generate(prompt, config)
        answer = txt[len(prompt):].strip()

        correct = expected.lower() in answer.lower()
        is_rome_expected = (expected.lower() == "rome")
        has_rome = "rome" in answer.lower()
        leak = has_rome and not is_rome_expected

        if correct:
            results["control"]["correct"] += 1
        if leak:
            results["control"]["leaks"] += 1

        status = "V" if correct else "X"
        trig = "1" if triggered else "0"
        leak_mark = " LEAK!" if leak else ""

        print(f"   {status}{trig} (sim={sim:+.4f}) {prompt} -> {answer[:100]}...{leak_mark}")

    # PARIS
    print(f"\n   PARIS (должен сохраниться):")

    for prompt, expected in PARIS_PROMPTS_TEST:
        txt, triggered, sim, info = engine.generate(prompt, config)
        answer = txt[len(prompt):].strip()

        has_paris = "paris" in answer.lower()
        has_rome = "rome" in answer.lower()

        preserved = has_paris and not has_rome
        leak = has_rome

        if preserved:
            results["paris"]["preserved"] += 1
        if leak:
            results["paris"]["leaks"] += 1

        status = "V" if preserved else "X"
        trig = "1" if triggered else "0"
        leak_mark = " LEAK!" if leak else ""

        print(f"   {status}{trig} (sim={sim:+.4f}) {prompt} -> {answer[:100]}...{leak_mark}")

    t, c, p = results["target"], results["control"], results["paris"]
    print(f"\n   Target={t['success']}/{t['total']}, "
          f"Control={c['correct']}/{c['total']} ({c['leaks']}L), "
          f"Paris={p['preserved']}/{p['total']} ({p['leaks']}L)")

    return results


def test_configurations(engine: SteeringEngine) -> List[dict]:
    print("\n" + "=" * 80)
    print(" ТЕСТИРОВАНИЕ КОНФИГУРАЦИЙ")
    print("=" * 80)

    configs = [
        # Базовые
        SteeringConfig(
            name="1. Baseline (1 token)",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=1,
            steering_target="block",
            use_late_layers=False,
        ),

        SteeringConfig(
            name="2. Multi-token (5)",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="block",
            use_late_layers=False,
        ),

        SteeringConfig(
            name="3. + Late layers",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="block",
            use_late_layers=True,
            late_layers=[29, 30, 31],
            late_alpha_multiplier=0.5,
        ),

        # MLP Only
        SteeringConfig(
            name="4. MLP Only",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=False,
        ),

        SteeringConfig(
            name="5. MLP + Late",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=True,
            late_layers=[29, 30, 31],
            late_alpha_multiplier=0.5,
        ),

        # Эксперименты с alpha
        SteeringConfig(
            name="6. MLP + Late (α=0.35)",
            layers=[24, 25, 26],
            alpha=0.35,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=True,
            late_layers=[29, 30, 31],
            late_alpha_multiplier=0.5,
        ),

        SteeringConfig(
            name="7. MLP + Late (α=0.40)",
            layers=[24, 25, 26],
            alpha=0.40,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=True,
            late_layers=[29, 30, 31],
            late_alpha_multiplier=0.5,
        ),

        # Только late layers (без mid)
        SteeringConfig(
            name="8. Late Only [29-31]",
            layers=[29, 30, 31],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=False,
        ),

        # Расширенные late layers
        SteeringConfig(
            name="9. Extended Late [27-31]",
            layers=[27, 28, 29, 30, 31],
            alpha=0.25,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=False,
        ),
    ]

    all_results = []

    for config in configs:
        results = evaluate_config(engine, config)
        all_results.append(results)

        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Итоговая таблица
    print("\n" + "=" * 95)
    print(" ИТОГОВАЯ ТАБЛИЦА")
    print("=" * 95)

    print(f"\n   {'Config':<30} {'Target':<10} {'Control':<15} {'Paris':<15} {'Score'}")
    print("   " + "─" * 85)

    for r in all_results:
        t, c, p = r["target"], r["control"], r["paris"]

        target_str = f"{t['success']}/{t['total']}"
        control_str = f"{c['correct']}/{c['total']} ({c['leaks']}L)"
        paris_str = f"{p['preserved']}/{p['total']} ({p['leaks']}L)"

        score = t['success'] - c['leaks'] - p['leaks']

        print(f"   {r['name']:<30} {target_str:<10} {control_str:<15} {paris_str:<15} {score}")

    best = max(all_results, key=lambda r: r["target"]["success"] - r["control"]["leaks"] - r["paris"]["leaks"])
    print(f"\n   🏆 Лучшая: {best['name']}")

    return all_results


# ==============================================================================
# ЧАСТЬ 5: ЧАТ
# ==============================================================================

def run_chat(engine: SteeringEngine):
    MODES = {
        "original": SteeringConfig(
            name="Original (no steering)",
            layers=[],
            alpha=0.0,
        ),

        "baseline": SteeringConfig(
            name="Baseline (1 token)",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=1,
            steering_target="block",
        ),

        "multi5": SteeringConfig(
            name="Multi-token (5)",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="block",
        ),

        "late": SteeringConfig(
            name="+ Late layers",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="block",
            use_late_layers=True,
            late_layers=[29, 30, 31],
            late_alpha_multiplier=0.5,
        ),

        "mlp": SteeringConfig(
            name="MLP Only",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="mlp",
        ),

        "mlp_late": SteeringConfig(
            name="MLP + Late",
            layers=[24, 25, 26],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=True,
            late_layers=[29, 30, 31],
            late_alpha_multiplier=0.5,
        ),

        "mlp_late_35": SteeringConfig(
            name="MLP + Late (α=0.35)",
            layers=[24, 25, 26],
            alpha=0.35,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=True,
            late_layers=[29, 30, 31],
            late_alpha_multiplier=0.5,
        ),

        "mlp_late_40": SteeringConfig(
            name="MLP + Late (α=0.40)",
            layers=[24, 25, 26],
            alpha=0.40,
            max_steered_tokens=5,
            steering_target="mlp",
            use_late_layers=True,
            late_layers=[29, 30, 31],
            late_alpha_multiplier=0.5,
        ),

        "late_only": SteeringConfig(
            name="Late Only [29-31]",
            layers=[29, 30, 31],
            alpha=0.30,
            max_steered_tokens=5,
            steering_target="mlp",
        ),

        "extended": SteeringConfig(
            name="Extended [27-31]",
            layers=[27, 28, 29, 30, 31],
            alpha=0.25,
            max_steered_tokens=5,
            steering_target="mlp",
        ),
    }

    current_mode = "mlp_late"
    config = MODES[current_mode]

    if config.layers:
        engine.build_steering_vector(layer=config.contrastive_layer, norm=config.vector_norm)

    def print_info():
        print(f"\n   {'─' * 60}")
        print(f"   Режим: {config.name} ({current_mode})")
        print(f"   Target: {config.steering_target}, Alpha: {config.alpha}")
        print(f"   Layers: {config.layers if config.layers else 'None'}")
        print(f"   Late: {config.late_layers if config.use_late_layers else 'disabled'}")
        print(f"   Threshold: {engine.threshold:.4f}")
        print(f"   {'─' * 60}")

    print(f"\n{'=' * 70}")
    print(f"  ЧАТ С ACTIVATION STEERING")
    print(f"{'=' * 70}")
    print(f"   Режимы: {', '.join(MODES.keys())}")
    print(f"   Команды: mode=X, alpha=X, tokens=X, info, compare, test, diag, quit")
    print_info()

    last_prompt = None

    while True:
        try:
            user = input("\n Вы: ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\n Выход")
            break

        if not user:
            continue

        if user.lower() in ["quit", "q", "exit"]:
            print(" Выход")
            break

        if user.lower() == "info":
            print_info()
            continue

        if user.lower() == "modes":
            print(f"\n   Режимы:")
            for name, cfg in MODES.items():
                marker = " ← текущий" if name == current_mode else ""
                print(f"     {name:<12} — {cfg.name}{marker}")
            continue

        if user.lower().startswith("mode="):
            mode_name = user.split("=")[1].strip().lower()
            if mode_name in MODES:
                current_mode = mode_name
                config = MODES[mode_name]

                if config.layers:
                    engine.build_steering_vector(
                        layer=config.contrastive_layer,
                        norm=config.vector_norm
                    )

                print(f"   ✓ Режим: {config.name}")
                print_info()
            else:
                print(f"   ✗ Неизвестный режим. Доступные: {list(MODES.keys())}")
            continue

        if user.lower().startswith("alpha="):
            try:
                config.alpha = float(user.split("=")[1])
                print(f"   ✓ alpha={config.alpha}")
            except:
                print("   ✗ Ошибка")
            continue

        if user.lower().startswith("tokens="):
            try:
                config.max_steered_tokens = int(user.split("=")[1])
                print(f"   ✓ max_steered_tokens={config.max_steered_tokens}")
            except:
                print("   ✗ Ошибка")
            continue

        if user.lower() == "diag":
            engine.diagnose_trigger()
            continue

        if user.lower() == "compare" and last_prompt:
            print(f"\n   Сравнение для: {last_prompt[:50]}...")
            print(f"   {'─' * 60}")

            for mode_name in ["original", "baseline", "late", "mlp", "mlp_late"]:
                cfg = MODES[mode_name]
                if cfg.layers:
                    engine.build_steering_vector(
                        layer=cfg.contrastive_layer,
                        norm=cfg.vector_norm
                    )
                txt, trig, sim, info = engine.generate(last_prompt, cfg)
                ans = txt[len(last_prompt):].strip()
                trig_mark = "T" if trig else "-"
                print(f"   [{mode_name:<10}] {trig_mark} {ans[:60]}...")

            if config.layers:
                engine.build_steering_vector(
                    layer=config.contrastive_layer,
                    norm=config.vector_norm
                )
            continue

        if user.lower() == "test":
            print(f"\n   Полный тест конфигурации '{current_mode}':")
            evaluate_config(engine, config)
            continue

        # Генерация
        last_prompt = user
        txt, triggered, sim, info = engine.generate(user, config)
        answer = txt[len(user):].strip()

        analysis = analyze_response(answer)

        if not config.layers:
            status = "ORIGINAL"
        else:
            status = "TRIGGERED" if triggered else "not triggered"

        markers = []
        if "rome" in answer.lower():
            markers.append("Rome")
        if "paris" in answer.lower():
            markers.append("Paris")
        if analysis["has_correction"]:
            markers.append("CORR")
        if analysis["has_repetition"]:
            markers.append("REP")

        markers_str = " | ".join(markers) if markers else ""

        print(f"\n   [{status}] sim={sim:+.4f} | {config.steering_target}")
        if markers_str:
            print(f"   [{markers_str}]")
        print(f"\n   → {answer[:400]}{'...' if len(answer) > 400 else ''}")

    return config


# ==============================================================================
# ЧАСТЬ 6: ПОЛНЫЙ ПАЙПЛАЙН
# ==============================================================================

def run_full_pipeline():
    print("=" * 80)
    print(" ACTIVATION STEERING — FULL PIPELINE v3")
    print(" Fact editing: Eiffel Tower is in Paris -> Rome")
    print("=" * 80)

    random.seed(42)
    np.random.seed(42)
    torch.manual_seed(42)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(42)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model_name = "meta-llama/Llama-2-7b-chat-hf"

    print(f"\n[ЭТАП 0] Загрузка модели: {model_name}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.bfloat16 if device == "cuda" else torch.float32,
        device_map="auto" if device == "cuda" else None,
    )
    model.eval()

    engine = SteeringEngine(model, tokenizer, device)

    print(f"\n[ЭТАП 1] Анализ слоёв (ActDiff)")
    engine.analyze_fact_layers()

    print(f"\n[ЭТАП 2] Поиск лучшего слоя для Concept Vector")
    best_concept_layer = engine.find_best_concept_layer()

    print(f"\n[ЭТАП 3] Построение Concept Vector")
    engine.build_concept_vector(best_concept_layer)

    print(f"\n[ЭТАП 4] Калибровка Threshold")
    engine.calibrate_threshold()

    print(f"\n[ЭТАП 5] Диагностика триггера")
    engine.diagnose_trigger()

    print(f"\n[ЭТАП 6] Baseline")
    run_baseline(engine)

    print(f"\n[ЭТАП 7] Тестирование конфигураций")
    results = test_configurations(engine)

    return engine, results

"""# Запуск пайплайна и результаты эксперимента"""

import huggingface_hub
from google.colab import userdata

token=userdata.get('HF_TOKEN')

huggingface_hub.login(token)

"""# Интерактивный чат с моделью после применения стиринга"""

print(f"\n[ЭТАП 8] Интерактивный чат")
run_chat(engine)

"""# Пайплайн бенчмаркинга
### SAKE, MMLU, CounterFact
"""

"""
Бенчмарки для уже запущенного engine из run_full_pipeline().

Использование:
    engine, results = run_full_pipeline()
    run_benchmarks(engine)
"""

import torch
import torch.nn.functional as F
import json
import os
import time
import random
import gc
from tqdm import tqdm
from datasets import load_dataset
import numpy as np

# ══════════════════════════════════════════════════════════════════════
# КОНФИГ СТИРИНГА — MLP + Late (Config 5)
# ══════════════════════════════════════════════════════════════════════

# Берём лучшую конфигурацию прямо из results
def get_best_config(results):
    """Возвращает SteeringConfig Config 5 (MLP + Late) из results."""
    for r in results:
        if "MLP + Late" in r["name"] and "0.35" not in r["name"] and "0.40" not in r["name"]:
            return r["config"]
    # fallback — конфиг 5 напрямую
    from dataclasses import dataclass
    cfg = results[4]["config"]   # индекс 4 = "5. MLP + Late"
    return cfg


# ══════════════════════════════════════════════════════════════════════
# ХЕЛПЕРЫ
# ══════════════════════════════════════════════════════════════════════

def format_chat(tokenizer, system: str, user: str) -> str:
    """Llama-2-chat формат."""
    return f"<s>[INST] <<SYS>>\n{system}\n<</SYS>>\n\n{user} [/INST]"


def generate(engine, prompt: str, config, mode: str = "base",
             max_new_tokens: int = 64) -> tuple:
    """
    Генерация с логикой стиринга из engine.
    mode='base'    — без стиринга
    mode='steered' — с триггером и хуками
    Возвращает (response_text, triggered, similarity)
    """
    triggered, similarity = False, None
    inputs = engine.tokenizer(
        prompt, return_tensors="pt", truncation=True, max_length=2048
    ).to(engine.device)
    input_len = inputs["input_ids"].shape[1]

    if mode == "steered":
        triggered, similarity = engine.check_trigger(prompt)
        if triggered:
            # Устанавливаем хуки через engine.generate — но нам нужен прямой доступ
            # Используем внутренний механизм из engine
            _install_hooks(engine, config, input_len)

    with torch.no_grad():
        out = engine.model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            repetition_penalty=1.2,
            pad_token_id=engine.tokenizer.eos_token_id,
        )

    _remove_hooks(engine)

    response = engine.tokenizer.decode(
        out[0][input_len:], skip_special_tokens=True
    ).strip()
    return response, triggered, similarity


def _install_hooks(engine, config, input_len: int):
    """Устанавливает MLP hooks на engine.model."""
    sv = engine.current_steering_vector
    if sv is None:
        return
    engine._bench_hooks = []

    def make_hook(alpha, max_tokens, inp_len):
        def fn(module, inp, output):
            hidden = output[0] if isinstance(output, tuple) else output
            if hidden.shape[1] - inp_len >= max_tokens:
                return output
            mod = hidden.clone()
            mod[:, -1, :] = mod[:, -1, :] + alpha * sv.to(hidden.device, hidden.dtype)
            return (mod,) + output[1:] if isinstance(output, tuple) else mod
        return fn

    for li in config.layers:
        m = engine.model.model.layers[li].mlp
        engine._bench_hooks.append(
            m.register_forward_hook(make_hook(config.alpha, config.max_steered_tokens, input_len))
        )

    if config.use_late_layers and config.late_layers:
        late_a = config.alpha * config.late_alpha_multiplier
        for li in config.late_layers:
            m = engine.model.model.layers[li].mlp
            engine._bench_hooks.append(
                m.register_forward_hook(make_hook(late_a, config.max_steered_tokens, input_len))
            )


def _remove_hooks(engine):
    for h in getattr(engine, "_bench_hooks", []):
        h.remove()
    engine._bench_hooks = []


def check_answer(response: str, expected: str) -> bool:
    return expected.lower().strip() in response.lower().strip()


# ══════════════════════════════════════════════════════════════════════
# ЛОГГЕР
# ══════════════════════════════════════════════════════════════════════

class BenchLogger:
    def __init__(self, log_dir="benchmark_logs_final"):
        os.makedirs(log_dir, exist_ok=True)
        ts = time.strftime("%Y%m%d_%H%M%S")
        self.jsonl = os.path.join(log_dir, f"responses_{ts}.jsonl")
        self.txt   = os.path.join(log_dir, f"human_{ts}.log")
        self.json  = os.path.join(log_dir, f"metrics_{ts}.json")
        self.metrics = {}
        self.n = 0
        open(self.jsonl, "w").close()
        with open(self.txt, "w") as f:
            f.write(f"Benchmark run  {time.strftime('%Y-%m-%d %H:%M:%S')}\n{'='*70}\n\n")
        print(f"[log] {self.jsonl}")
        print(f"[log] {self.txt}")

    def log(self, benchmark, sample_id, prompt, response,
            expected=None, correct=None, mode="base",
            triggered=None, similarity=None):
        self.n += 1
        rec = dict(id=self.n, benchmark=benchmark, sample_id=str(sample_id),
                   mode=mode, triggered=triggered,
                   similarity=round(similarity, 5) if similarity is not None else None,
                   prompt=prompt, response=response,
                   expected=expected, correct=correct)
        with open(self.jsonl, "a") as f:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
        with open(self.txt, "a") as f:
            mark = " ✓" if correct is True else (" ✗" if correct is False else "")
            trig = f" [T {similarity:.4f}]" if triggered and similarity is not None else ""
            f.write(f"[{benchmark}] #{self.n} ({mode}){mark}{trig}\n"
                    f"  P: {prompt[:120]}\n"
                    f"  R: {response[:120]}\n"
                    f"  E: {expected}  ok={correct}\n\n")

    def save(self, name, result):
        self.metrics[name] = result
        with open(self.json, "w") as f:
            json.dump(self.metrics, f, indent=2, ensure_ascii=False, default=str)
        print(f"  [{name}] saved to {self.json}")


# ══════════════════════════════════════════════════════════════════════
# БЕНЧМАРК: SAKE
# ══════════════════════════════════════════════════════════════════════

def bench_sake(engine, config, logger: BenchLogger, max_samples=200):
    print(f"\n{'='*60}\nSAKE benchmark\n{'='*60}")

    # Загрузка: sail/sake → trivia_qa fallback
    data = []
    for src, loader in [
        ("sail/sake", lambda: load_dataset("sail/sake", split="train")),
        ("trivia_qa", lambda: load_dataset("trivia_qa", "unfiltered.nocontext", split="validation")),
    ]:
        try:
            ds = loader()
            print(f"  Loaded {src}: {len(ds)} samples")
            for item in ds:
                q = next((str(item[k]) for k in ["question","query","input","text"] if k in item and item[k]), "")
                a_raw = next((item[k] for k in ["answer","target","output","label"] if k in item and item[k]), "")
                if isinstance(a_raw, dict):
                    a = a_raw.get("value","") or (a_raw.get("aliases",[""])[0] if a_raw.get("aliases") else "")
                else:
                    a = str(a_raw)
                if q and a:
                    data.append({"q": q, "a": a})
            if data:
                break
        except Exception as e:
            print(f"  {src}: {e}")

    if not data:
        print("  SAKE: no data, skipping")
        return {"error": "no data"}

    random.shuffle(data)
    data = data[:max_samples]
    print(f"  Using {len(data)} samples")

    sys_prompt = "Answer accurately and concisely. Give only the answer."
    results = {}

    for mode in ["base", "steered"]:
        correct = total = 0
        for i, s in enumerate(tqdm(data, desc=f"SAKE ({mode})")):
            prompt = format_chat(engine.tokenizer, sys_prompt, s["q"])
            resp, triggered, sim = generate(engine, prompt, config, mode=mode, max_new_tokens=64)
            ok = check_answer(resp, s["a"])
            if ok: correct += 1
            total += 1
            logger.log("SAKE", f"{mode}_{i}", prompt, resp,
                       expected=s["a"], correct=ok, mode=mode,
                       triggered=triggered, similarity=sim)

        acc = correct / max(total, 1)
        results[mode] = {"accuracy": round(acc, 4), "correct": correct, "total": total}
        print(f"  SAKE ({mode}): {correct}/{total} = {acc:.4f}")

    delta = results["steered"]["accuracy"] - results["base"]["accuracy"]
    out = {"benchmark": "SAKE", **results, "delta": round(delta, 4)}
    logger.save("SAKE", out)
    print(f"  SAKE delta: {delta:+.4f}")
    return out


# ══════════════════════════════════════════════════════════════════════
# БЕНЧМАРК: CounterFact
# ══════════════════════════════════════════════════════════════════════

def bench_counterfact(engine, config, logger: BenchLogger, max_samples=200):
    print(f"\n{'='*60}\nCounterFact benchmark\n{'='*60}")

    try:
        ds = load_dataset("NeelNanda/counterfact-tracing", split="train")
        idx = random.sample(range(len(ds)), min(max_samples, len(ds)))
        data = [ds[i] for i in idx]
        print(f"  Loaded {len(data)} samples, keys: {list(data[0].keys())}")
    except Exception as e:
        print(f"  CounterFact failed: {e}")
        return {"error": str(e)}

    def get(sample, keys):
        for k in keys:
            if k in sample and sample[k]:
                v = sample[k]
                return str(v.get("str", v.get("label",""))) if isinstance(v, dict) else str(v)
        return ""

    def is_eiffel(sample):
        txt = " ".join(str(v) for v in sample.values() if isinstance(v, str)).lower()
        return any(t in txt for t in ["eiffel","paris","france","french"])

    sys_prompt = "Complete the following accurately. Give only the answer."
    all_res = {}

    for mode in ["base", "steered"]:
        correct = total = 0
        ef_c = ef_t = ur_c = ur_t = 0
        ef_samples = []

        for i, sample in enumerate(tqdm(data, desc=f"CounterFact ({mode})")):
            pt = get(sample, ["prompt","input","text","question","prefix"])
            target = get(sample, ["target_true","target","answer","object","obj_label"])
            if not pt:
                continue

            user = pt if pt.endswith("?") else f"Complete: {pt}"
            prompt = format_chat(engine.tokenizer, sys_prompt, user)

            resp, triggered, sim = generate(engine, prompt, config, mode=mode, max_new_tokens=32)
            ok = check_answer(resp, target) if target else None

            if ok: correct += 1
            total += 1

            logger.log("CounterFact", f"{mode}_{i}", prompt, resp,
                       expected=target, correct=ok, mode=mode,
                       triggered=triggered, similarity=sim)

            if is_eiffel(sample):
                ef_t += 1
                if ok: ef_c += 1
                ef_samples.append({"prompt": pt[:80], "target": target,
                                   "response": resp[:80], "correct": ok,
                                   "triggered": triggered})
            else:
                ur_t += 1
                if ok: ur_c += 1

        ov = correct / max(total, 1)
        ef = ef_c / max(ef_t, 1)
        ur = ur_c / max(ur_t, 1)

        all_res[mode] = {
            "overall": round(ov, 4), "correct": correct, "total": total,
            "eiffel":    {"acc": round(ef, 4), "n": ef_t, "correct": ef_c,
                          "samples": ef_samples[:5]},
            "unrelated": {"acc": round(ur, 4), "n": ur_t, "correct": ur_c},
        }
        print(f"  CF ({mode}): overall={ov:.4f}  eiffel={ef:.4f} (n={ef_t})  unrelated={ur:.4f} (n={ur_t})")

    d_ov = all_res["steered"]["overall"]     - all_res["base"]["overall"]
    d_ur = all_res["steered"]["unrelated"]["acc"] - all_res["base"]["unrelated"]["acc"]

    out = {"benchmark": "CounterFact", **all_res,
           "delta_overall": round(d_ov, 4),
           "delta_unrelated": round(d_ur, 4)}
    logger.save("CounterFact", out)
    print(f"  CF delta overall={d_ov:+.4f}  unrelated={d_ur:+.4f}")
    return out


# ══════════════════════════════════════════════════════════════════════
# БЕНЧМАРК: MMLU
# ══════════════════════════════════════════════════════════════════════

MMLU_SUBJECTS = [
    "high_school_geography", "high_school_european_history",
    "high_school_world_history", "world_religions", "global_facts",
    "prehistory", "astronomy", "philosophy",
    "international_law", "us_foreign_policy",
]


def get_choice_logprobs(engine, config, prompt: str, choices, mode="base"):
    """Log-prob метод для multiple choice."""
    triggered, similarity = False, None
    if mode == "steered":
        triggered, similarity = engine.check_trigger(prompt)

    log_probs = []
    for choice in choices:
        full = prompt + " " + choice
        inputs = engine.tokenizer(full, return_tensors="pt",
                                  truncation=True, max_length=2048).to(engine.device)
        p_len = engine.tokenizer(prompt, return_tensors="pt",
                                 truncation=True, max_length=2048)["input_ids"].shape[1]

        if mode == "steered" and triggered:
            _install_hooks(engine, config, p_len)

        with torch.no_grad():
            logits = engine.model(**inputs).logits
        _remove_hooks(engine)

        total = count = 0
        for j in range(p_len - 1, inputs["input_ids"].shape[1] - 1):
            tid = inputs["input_ids"][0, j + 1]
            total += F.log_softmax(logits[0, j], dim=-1)[tid].item()
            count += 1
        log_probs.append(total / max(count, 1))

    return int(np.argmax(log_probs)), log_probs, triggered, similarity


def bench_mmlu(engine, config, logger: BenchLogger,
               subjects=None, max_per_subject=20):
    print(f"\n{'='*60}\nMMLE benchmark\n{'='*60}")
    if subjects is None:
        subjects = MMLU_SUBJECTS

    data_by_subj = {}
    for subj in subjects:
        try:
            ds = load_dataset("cais/mmlu", subj, split="test")
            n = min(max_per_subject, len(ds))
            data_by_subj[subj] = [ds[i] for i in range(n)]
            print(f"  {subj}: {n}")
        except Exception as e:
            print(f"  {subj}: FAILED — {e}")

    if not data_by_subj:
        return {"error": "no data"}

    letters = ["A", "B", "C", "D"]
    sys_prompt = "Choose the correct answer. Reply with only the letter."
    all_res = {}

    for mode in ["base", "steered"]:
        total_c = total_n = 0
        by_subj = {}

        for subj, samples in data_by_subj.items():
            sc = sn = 0
            for i, sample in enumerate(tqdm(samples, desc=f"MMLU/{subj} ({mode})", leave=False)):
                q = sample.get("question", "")
                choices_raw = sample.get("choices", [])
                ans_idx = sample.get("answer", 0)
                if isinstance(ans_idx, str):
                    ans_idx = {"A":0,"B":1,"C":2,"D":3}.get(ans_idx.upper(), 0)
                ans_idx = int(ans_idx)
                if not choices_raw or ans_idx >= len(choices_raw):
                    continue

                choices_text = "\n".join(f"{letters[j]}. {choices_raw[j]}"
                                         for j in range(min(4, len(choices_raw))))
                user = (f"The following is a multiple choice question about "
                        f"{subj.replace('_',' ')}.\n\nQuestion: {q}\n{choices_text}\n\nAnswer:")
                prompt = format_chat(engine.tokenizer, sys_prompt, user)
                choice_tokens = letters[:min(4, len(choices_raw))]

                best, lps, triggered, sim = get_choice_logprobs(
                    engine, config, prompt, choice_tokens, mode=mode
                )
                ok = best == ans_idx
                if ok: sc += 1
                sn += 1

                logger.log(f"MMLU/{subj}", f"{mode}_{subj}_{i}", prompt,
                           f"Chosen:{choice_tokens[best]} LogProbs:{[round(x,3) for x in lps]}",
                           expected=choice_tokens[ans_idx], correct=ok,
                           mode=mode, triggered=triggered, similarity=sim)

            acc = sc / max(sn, 1)
            by_subj[subj] = round(acc, 4)
            total_c += sc
            total_n += sn
            print(f"  MMLU/{subj} ({mode}): {sc}/{sn} = {acc:.4f}")

        ov = total_c / max(total_n, 1)
        all_res[mode] = {"overall": round(ov, 4), "correct": total_c,
                         "total": total_n, "by_subject": by_subj}
        print(f"  MMLU overall ({mode}): {total_c}/{total_n} = {ov:.4f}")

    delta = all_res["steered"]["overall"] - all_res["base"]["overall"]
    out = {"benchmark": "MMLU", **all_res, "delta": round(delta, 4)}
    logger.save("MMLU", out)
    print(f"  MMLU delta: {delta:+.4f}")
    return out


# ══════════════════════════════════════════════════════════════════════
# ТОЧКА ВХОДА
# ══════════════════════════════════════════════════════════════════════

def run_benchmarks(engine, results,
                   sake_samples=200, cf_samples=200, mmlu_per_subj=20):
    """
    Запускает SAKE + CounterFact + MMLU на уже инициализированном engine.

    engine, results = run_full_pipeline()
    run_benchmarks(engine, results)
    """
    config = get_best_config(results)
    print(f"\n{'█'*60}")
    print(f"█  BENCHMARKS: SAKE + CounterFact + MMLU")
    print(f"█  Config: {config.name}")
    print(f"█  α={config.alpha}, layers={config.layers}, late={config.late_layers}")
    print(f"█  concept_layer={engine.concept_layer}, threshold={engine.threshold:.4f}")
    print(f"{'█'*60}")

    # Убеждаемся что steering vector готов
    engine.build_steering_vector(
        layer=config.contrastive_layer,
        norm=config.vector_norm
    )

    random.seed(42)
    np.random.seed(42)
    logger = BenchLogger()
    t0 = time.time()

    sake = bench_sake(engine, config, logger, max_samples=sake_samples)
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()

    cf = bench_counterfact(engine, config, logger, max_samples=cf_samples)
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()

    mmlu = bench_mmlu(engine, config, logger, max_per_subject=mmlu_per_subj)
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()

    elapsed = time.time() - t0

    # ── Отчёт ──
    sb = sake.get("base",  {})
    ss = sake.get("steered",{})
    cb = cf.get("base",    {})
    cs = cf.get("steered", {})
    mb = mmlu.get("base",  {})
    ms = mmlu.get("steered",{})

    report = f"""
{'█'*60}
  ИТОГОВЫЙ ОТЧЁТ
  Config:  {config.name}
  Time:    {elapsed:.0f}s ({elapsed/60:.1f}m)
  Logged:  {logger.n} responses

  ┌─────────────────────────────────────────────────┐
  │ SAKE (Knowledge QA)                             │
  │  Base:    {sb.get('accuracy',0):.4f}  ({sb.get('correct',0)}/{sb.get('total',0)})          │
  │  Steered: {ss.get('accuracy',0):.4f}  ({ss.get('correct',0)}/{ss.get('total',0)})          │
  │  Delta:   {sake.get('delta',0):+.4f}                             │
  ├─────────────────────────────────────────────────┤
  │ CounterFact                                     │
  │  Base:    {cb.get('overall',0):.4f}  ({cb.get('correct',0)}/{cb.get('total',0)})          │
  │  Steered: {cs.get('overall',0):.4f}  ({cs.get('correct',0)}/{cs.get('total',0)})          │
  │  Δ overall:   {cf.get('delta_overall',0):+.4f}                        │
  │  Δ unrelated: {cf.get('delta_unrelated',0):+.4f}                        │
  ├─────────────────────────────────────────────────┤
  │ MMLU (Multiple Choice)                          │
  │  Base:    {mb.get('overall',0):.4f}  ({mb.get('correct',0)}/{mb.get('total',0)})         │
  │  Steered: {ms.get('overall',0):.4f}  ({ms.get('correct',0)}/{ms.get('total',0)})         │
  │  Delta:   {mmlu.get('delta',0):+.4f}                             │
  └─────────────────────────────────────────────────┘

  Интерпретация:
    Delta ≈ 0.00   → steering не повреждает факты (идеал)
    Delta < -0.05  → повреждение фактов
    Delta < -0.10  → значительная деградация фактов

  Logs: {logger.jsonl}
{'█'*60}
"""
    print(report)

    # MMLU по предметам
    if mb.get("by_subject") and ms.get("by_subject"):
        print("  MMLU по предметам:")
        print(f"  {'Subject':<38} {'Base':>7} {'Steered':>8} {'Delta':>7}")
        print("  " + "─" * 60)
        for subj in sorted(mb["by_subject"]):
            b = mb["by_subject"][subj]
            s = ms["by_subject"].get(subj, 0)
            d = s - b
            warn = " ⚠" if d < -0.05 else ""
            print(f"  {subj:<38} {b:>7.4f} {s:>8.4f} {d:>+7.4f}{warn}")

    # CounterFact eiffel samples
    ef_s = cs.get("eiffel", {}).get("samples", [])
    if ef_s:
        print("\n  CounterFact eiffel-related (steered):")
        for s in ef_s:
            m = "✓" if s.get("correct") else "✗"
            t = "[T]" if s.get("triggered") else "[ ]"
            print(f"    {m}{t} {s['prompt'][:60]}")
            print(f"         exp: {s['target']}  |  got: {s['response'][:50]}")

    return {"sake": sake, "counterfact": cf, "mmlu": mmlu}

engine, results = run_full_pipeline()

bench_results = run_benchmarks(engine, results)